models:
  url: http://34.133.242.53:30001/api/projects/default/models/tags/production
  token: rasaXToken
  wait_time_between_pulls: 10
tracker_store:
  type: sql
  dialect: postgresql
  url: 127.0.0.1
  port: 30027
  username: postgres
  password: password
  db: tracker
  login_db: rasa
event_broker:
  type: pika
  url: 127.0.0.1
  port: 30076
  username: user
  password: password
  queues:
  - rasa_production_events
action_endpoint:
  url: "http://localhost:5055/webhook"
